assets:
  npmrc: yegor256/home#assets/npmrc
install: |
  sudo apt-get -y update
  sudo gem install pdd -v 0.20.5
  sudo npm install --no-color --global gulp-cli
  npm install --no-color
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    gulp --no-color
    cp dist/colorizejs.min.js colorizejs-${tag}.min.js
    git add -f colorizejs-${tag}.min.js
    git commit -am "Added JS file for ${tag}"
    cp dist/colorizejs.min.js /tmp
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    cp /tmp/colorizejs.min.js .
    git add colorizejs.min.js
    cp colorizejs.min.js colorizejs-${tag}.min.js
    git add colorizejs-${tag}.min.js
    git commit --allow-empty -am "${tag}"
    git checkout "${branch}"
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
architect:
- yegor256
merge:
  script: |-
    gulp
    pdd -f /dev/null -v
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
