# SPDX-FileCopyrightText: Copyright (c) 2018 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
assets:
  npmrc: yegor256/home#assets/npmrc
install: |
  npm install --no-color
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    npx gulp --no-color
    cp dist/colorizejs.min.js colorizejs-${tag}.min.js
    git add -f colorizejs-${tag}.min.js
    git commit -am "Added JS file for ${tag}"
    cp dist/colorizejs.min.js /tmp
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    cp /tmp/colorizejs.min.js .
    git add colorizejs.min.js
    cp colorizejs.min.js colorizejs-${tag}.min.js
    git add colorizejs-${tag}.min.js
    git commit --allow-empty -am "${tag}"
    git checkout "${branch}"
    npm version "${tag}" --no-git-tag-version
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
merge:
  script: |-
    gulp
    pdd -f /dev/null -v
